export const getLetter = () => {
  return letters[Math.floor(Math.random() * letters.length)];
};

export const getCategory = () => {
  return categories[Math.floor(Math.random() * categories.length)];
};

export const getSomeCategories = (catQty: number) => {
  const cats: string[] = [];
  for (let i = 0; i < catQty; i++) cats.push(getCategory());
  return cats;
};

const letters = 'abcdefghijklmnoprstw';
const categories = [
  `a boy's name`,
  `US cities`,
  `things that are cold`,
  `things you don't want in the house`,
  `insects`,
  `things in a coffee bar`,
  `things you mix up`,
  `TV shows`,
  `things found in the ocean`,
  `kinds of weather`,
  `foods that kids hate`,
  `famous females`,
  `things found in a medicine cabinet`,
  `machines`,
  `hobbies`,
  `acronyms`,
  `things you plug in`,
  `animals`,
  `languages`,
  `things you grab on your way out the door`,
  `junk food`,
  `things that grow`,
  `things in an arcade`,
  `articles of clothing`,
  `desserts`,
  `things at a gas station`,
  `4-letter words`,
  `5-letter words`,
  `6-letter words`,
  `7-letter words`,
  `8-letter words`,
  `things you fold`,
  `things in a junk drawer`,
  `things you do online`,
  `things at the beach`,
  `things you dream about`,
  `tools`,
  `heroes`,
  `gifts / presents`,
  `terms of endearment`,
  `kinds of dances`,
  `things that are black`,
  `vehicles`,
  `things people gossip about`,
  `colors`,
  `things in a souvenir shop`,
  `items in your purse / wallet`,
  `sandwiches`,
  `things you can do with your feet`,
  `world leaders / politicians`,
  `school subjects`,
  `excuses for being late`,
  `ice cream flavors`,
  `things with balls`,
  `things in a park`,
  `non-US cities`,
  `stones / gems`,
  `musical instruments`,
  `song names`,
  `nicknames`,
  `things in the sky`,
  `things with windows`,
  `colleges / universities`,
  `fish`,
  `countries`,
  `things that have spots`,
  `things that smell bad`,
  `things you're afraid of`,
  `terms of measurement`,
  `items in your room`,
  `book titles`,
  `fictional characters`,
  `places to go on a date`,
  `magazines`,
  `capitals`,
  `kinds of candy`,
  `things you save up to buy`,
  `footwear`,
  `something you keep hidden`,
  `items in a suitcase`,
  `things with tails`,
  `crimes`,
  `things that are sticky`,
  `awards / ceremonies`,
  `cars`,
  `spices / herbs`,
  `bad habits`,
  `cosmetics / toiletries`,
  `celebrities`,
  `things to do with leftovers`,
  `reptiles / amphibians`,
  `rfads`,
  `leisure activities`,
  `things people can be allergic to`,
  `restaurants`,
  `notorious people`,
  `fruits`,
  `vegetables`,
  `weapons`,
  `toys`,
  `household chores`,
  `bodies of water`,
  `authors`,
  `Halloween costumes`,
  `funny movies`,
  `things that are round`,
  `song titles`,
  `parts of the body`,
  `ethnic foods`,
  `things you shout`,
  `birds`,
  `a girl's  name`,
  `ways to get from here to there`,
  `cooking terms`,
  `villains / monsters`,
  `flowers`,
  `things that weigh less than 1 pound`,
  `things that weigh more than 1 ton`,
  `things that need to be cleaned`,
  `things found in a desk`,
  `vacation spots`,
  `things at a hospital`,
  `words associated with money`,
  `items in a vending machine`,
  `movie titles`,
  `games`,
  `things that you wear`,
  `video game titles`,
  `things at a circus`,
  `states`,
  `things you throw away`,
  `occupations`,
  `foods you eat on holidays`,
  `cartoon characters`,
  `types of drink`,
  `musical groups`,
  `science things`,
  `things to do on a rainy day`,
  `trees`,
  `personality traits`,
  `things you can tie in a knot`,
  `things that are soft`,
  `things that are furry`,
  `things in a sci-fi movie`,
  `words with 4 different vowels`,
  `things that kids play with`,
  `things at a wedding`,
  `hot places`,
  `things in outer space`,
  `sounds`,
  `things at a diner`,
  `famous singers`,
  `things at an amusement park`,
  `worn above the waist`,
  `things that are bright`,
  `things that are dark`,
  `things that have numbers`,
  `found in a gym / health club / spa`,
  `chain stores / restaurants`,
  `ways to say hi and buy`,
  `things in the backyard`,
  `things people use to decorate their houses`,
  `items in an office`,
  `things in pairs or sets`,
  `artists`,
  `things in Las Vegas`,
  `things in New York`,
  `things in San Francisco`,
  `cities in Europe`,
  `European countries`,
  `Asian countries`,
  `cities in Asia`,
  `things at a zoo`,
  `things smaller than your fist`,
  `things that fly`,
  `things that swim`,
  `things that you eat on a diet`,
  `words ending in "-ly"`,
  `words ending in "-tion"`,
  `things found under the table`,
  `things in a hotel`,
  `things you can do 5 minutes or less`,
  `things with claws`,
  `party things`,
  `reasons to skip school / work`,
  `things that go well with chocolate`,
  `things in a mystery novel`,
  `websites`,
  `apps`,
  `loud things`,
  `quiet things`,
  `things you eat with a spoon`,
  `famous sayings`,
  `underground things`,
  `things in the wild west`,
  `things in an airport`,
  `words with double letters`,
  `things in fairy tales`,
  `anime series / movies`,
  `things that have stripes`,
  `menu items`,
  `words ending in "-n"`,
  `words ending in "-p"`,
  `words ending in "-t"`,
  `words ending in "-e"`,
  `words ending in "-c"`,
  `words ending in "-l"`,
  `things found in a desk`,
  `furniture`,
  `things that feel smooth`,
  `historical figures`,
  `things that have wheels`,
  `dairy products`,
  `things that are sweet`,
  `things that are sour`,
  `things that are salty`,
  `board games`,
  `tourist attractions`,
  `things in a fridge`,
  `things that jump / bounce`,
  `food / drink that is green`,
  `food / drink that is red`,
  `food / drink that is yellow`,
  `reasons to take out a loan`,
  `reasons to make a phone call`,
  `things to do on a date`,
  `things that make you smile`,
  `things that use a remote`,
  `breakfast foods`,
  `things you do every day`,
  `places to hang out`,
  `pizza toppings`,
  `things made of metal`,
  `things made of plastic`,
  `things you make`,
  `things made of wood`,
  `animals in books / movies`,
  `wireless things`,
  `things you shouldn't touch`,
  `things that are wet`,
  `things that are dry`,
  `things that are hot`,
  `things you don't want on a plane`,
  `ways to kill time`,
  `school supplies`,
  `people in uniform`,
  `college majors`,
  `children's books`,
  `diseases`,
  `things you get tickets for`,
  `kinds of soup`,
  `cooking utensils`,
  `insects`,
  `government agencies`,
  `companies`,
  `seafood`,
  `types of weather`,
  `weekend activities`,
  `junk food`,
  `things in a grocery store`,
  `things that can get you fired`,
  `historic events`,
  `things that are white`,
  `things that are blue`,
  `things that are red`,
  `things that are green`,
  `things that are yellow`,
  `things that are purple`,
  `things that are brown`,
  `items in a kitchen`,
  `things that have buttons`,
  `things that you do at work`,
  `foreign words used in English`,
  `store names`,
  `things that can kill you`,
  `street names`,
  `words associated with winter`,
  `words associated with summer`,
  `words associated with spring`,
  `words associated with autumn`,
  `items you take on a trip`,
  `items you take on a business trip`,
  `items you take on a cruise`,
  `internet lingo`,
  `holiday activities`,
  `things you get in the mail`,
  `things you sit in / on`,
  `things you sleep in / on`,
  `things you plug in`,
  `items in a suitcase`,
  `things you replace`,
  `things you refill`,
  `things that you store items in`,
  `computer parts`,
  `ice cream flavors`,
  `things you find in Asian grocers`,
  `things that taste bad`,
  `things that taste good`,
  `ways to prevent Covid`,
  `things to do during lockdown`,
  `things you can build with`,
  `things that cost more than $1M`,
  `things that cost more than $100k`,
  `things that cost more than $10k`,
  `things that cost less than $10`,
  `composers`,
  `things from 2020`,
  `things from the 19th century`,
  `things from the 20th century`,
  `things from the 21st century`,
  `things you buy from Amazon`,
  `things you buy from eBay`,
  `fast food`,
  `things you can vacuum up`,
  `pets`,
  `things vegans won't eat`,
  `things you pay monthly for`,
  `things with a wikipedia page`,
  `famous buildings`,
  `things commonly made in China`,
  `things you celebrate`,
  `things that are autonomous`,
  `things found at stores`,
  `things found at libraries`,
  `things found at schools`,
  `things found in a cafeteria`,
  `things found at work`,
  `things found in a bedroom`,
  `things found in a living room`,
  `things found outdoors`,
  `things found indoors`,
  `things that can open / close`,
  `things you can see from the roof`,
  `a unisex name`,
  `things that are hard`,
  `things that are fragile`,
  `things that can't be broken easily`,
  `things in a freezer`,
  `things that make you sick`,
  `things you take photos of`,
  `things you can climb on`,
  `things you do with 4+ people`,
  `phone games`,
  `things you find on social media`,
  `things people tweet about`,
  `things people google`,
  `things people don't want to lose`,
  `irreplaceable things`,
  `things you can stack`,
  `things that are sticky`,
  `trivia categories`,
  `things rich people have`,
  `something cute`,
  `foods you eat raw`,
  `verbs`,
  `nouns`,
  `adjectives`,
  `adverbs`,
  `things that can destroy the Earth`,
  `things you do on your phone`,
  `things you do on your computer`,
  `something longer than a car`,
  `something taller than 20 stories`,
  `something heavier than a car`,
  `something lighter than a pencil`,
  `things on a t-shirt`,
  `things you can hug`,
  `things you sniff`,
  `Pokemon`,
  `things on YouTube`,
  `things people keep hidden`,
  `things people show off`,
  `nutritious things`,
  `things that take time`,
  `sugary drinks`,
  `things you shouldn't eat too much`,
  `things old people like`,
  `things young people like`,
  `types of danger`,
  `things you practice`,
];
